config/routes.rb
Rails.application.routes.draw do
  # resources :users
  # get 'about', to: 'pages#about'
  root 'home#index'

  get 'home', to: 'home#index'
  resources :home, except: [:index]

  get 'dashboard', to: 'dashboard#index'

  get 'signup', to: 'users#new'
  resources :users, except: [:new, :index, :show]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true,
            uniqueness: { case_sensitive: true },
            length: { minimum: 5, maximum: 35 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # make views available to views
  helper_method :current_user, :logged_in?

  def current_user
    # return current_user or find one in the databas if they don;t exist
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    # redirect_to login if user is not logged in 
    redirect_to login_path if !logged_in?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # if logged_in then redirect user to dashboard
    redirect_to dashboard_path if logged_in?
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to dashboard_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to dashboard_path
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit]

  def new
    @user = User.new
  end

  def show
    redirect_to dashboard_path if logged_in?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to your Intercom #{@user.username}"
      redirect_to dashboard_path
    else
      render 'new'
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated succesfully!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    # byebug
    if current_user != @user
      flash[:danger] = "You can only edit your own account"
      redirect_to dashboard_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<br><br><br>
<h2 class="ui blue floated header">Welcome to your Intercom Dashboard  <em><%= current_user.username %></em> !</h2>
  <br><br>
    <% if logged_in? %>
      <h4><%= link_to 'Log Out', logout_path, method: :delete %></h4>
      <h4><%= link_to 'Edit Account', edit_user_path(current_user) %></h4>
    <% end %>
  <div class="ui clearing divider"></div>
<p></p>


<table class="ui compact celled definition table">
  <thead class="full-width">
    <tr>
      <th></th>
      <th>Name</th>
      <th>Registration Date</th>
      <th>E-mail address</th>
      <th>Premium Plan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="collapsing">
        <div class="ui fitted slider checkbox">
          <input type="checkbox"> <label></label>
        </div>
      </td>
      <td>John Lilki</td>
      <td>September 14, 2013</td>
      <td>jhlilk22@yahoo.com</td>
      <td>No</td>
    </tr>
    <tr>
      <td class="collapsing">
        <div class="ui fitted slider checkbox">
          <input type="checkbox"> <label></label>
        </div>
      </td>
      <td>Jamie Harington</td>
      <td>January 11, 2014</td>
      <td>jamieharingonton@yahoo.com</td>
      <td>Yes</td>
    </tr>
    <tr>
      <td class="collapsing">
        <div class="ui fitted slider checkbox">
          <input type="checkbox"> <label></label>
        </div>
      </td>
      <td>Jill Lewis</td>
      <td>May 11, 2014</td>
      <td>jilsewris22@yahoo.com</td>
      <td>Yes</td>
    </tr>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th></th>
      <th colspan="4">
        <div class="ui right floated small primary labeled icon button">
          <i class="user icon"></i> Add User
        </div>
        <div class="ui small  button">
          Approve
        </div>
        <div class="ui small  disabled button">
          Approve All
        </div>
      </th>
    </tr>
  </tfoot>
</table>

<table class="ui celled padded table">
  <thead>
    <tr><th class="single line">Evidence Rating</th>
    <th>Effect</th>
    <th>Efficacy</th>
    <th>Consensus</th>
    <th>Comments</th>
  </tr></thead>
  <tbody>
    <tr>
      <td>
        <h2 class="ui center aligned header">A</h2>
      </td>
      <td class="single line">
        Power Output
      </td>
      <td>
        <div class="ui star rating" data-rating="3" data-max-rating="3"></div>
      </td>
      <td class="right aligned">
        80% <br>
        <a href="#">18 studies</a>
      </td>
      <td>Creatine supplementation is the reference compound for increasing muscular creatine levels; there is variability in this increase, however, with some nonresponders.</td>
    </tr>
    <tr>
      <td>
        <h2 class="ui center aligned header">A</h2>
      </td>
      <td class="single line">
        Weight
      </td>
      <td>
        <div class="ui star rating" data-rating="3" data-max-rating="3"></div>
      </td>
      <td class="right aligned">
        100% <br>
        <a href="#">65 studies</a>
      </td>
      <td>Creatine is the reference compound for power improvement, with numbers from one meta-analysis to assess potency</td>
    </tr>
  </tbody>
  <tfoot>
    <tr><th colspan="5">
      <div class="ui right floated pagination menu">
        <a class="icon item">
          <i class="left chevron icon"></i>
        </a>
        <a class="item">1</a>
        <a class="item">2</a>
        <a class="item">3</a>
        <a class="item">4</a>
        <a class="icon item">
          <i class="right chevron icon"></i>
        </a>
      </div>
    </th>
  </tr></tfoot>
</table>

app/views/home/index.html.erb
<br><br><br>

<div class="ui placeholder segment">
  <div class="ui one column very relaxed stackable grid">
    <div class="column center">
      <h1 class="ui blue floated header">Intercom Dashboard</h1>
        <br><br>
          <% if logged_in? %>
            <h3><%= link_to 'Log out', logout_path, method: :delete %></h3>
          <% else %>
            <h3><%= link_to 'Log in', login_path %></h3>
            <h3><%= link_to 'Signup', signup_path %></h3>
          <% end %>
      <p></p>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
  <%= link_to "Dashboard", root_path, class: "item" %>
<% end %>
<div class="right menu">
  <div class="ui dropdown item">Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <%= link_to "Log in", login_path, class: "ui primary button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntercomDashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
     <div class="ui container">
      <%= render 'layouts/navigation' %>
     </div>
    </div>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "ui form", role: "form"}) do |f| %>

      <%= f.label :username %>

      <%= f.text_field :username, class: "ui fluid form", placeholder: "Enter username", autofocus: true %>
      <br><br>


      <%= f.label :email %>

      <%= f.email_field :email, class: "ui fluid form", placeholder: "Enter email" %>
      <br><br>


      <%= f.label :password %>

      <%= f.password_field :password, class: "ui fluid form", placeholder: "Enter password" %>
      <br><br><br>


      <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'ui primary button') %>

<% end %>

app/views/users/edit.html.erb
<br><br><br>

  <h2 class="ui blue floated header">Edit your account details</h2>
  <div class="ui clearing divider"></div>

<br>
<%= render 'form' %>

app/views/users/new.html.erb
<br><br><br>

  <h2 class="ui blue floated header">Sign up to Intercom Dashboard</h2>
  <div class="ui clearing divider"></div>
  <p></p>

<br>
<%= render 'form' %>